# Generated by Django 3.0.2 on 2020-03-14 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
        migrations.RemoveField(
            model_name='account',
            name='view',
        ),
        migrations.AlterField(
            model_name='account',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='accountactivity',
            name='activityUpdatedDate',
            field=models.DateTimeField(verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='accountactivity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih'),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='accountpermission',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih'),
        ),
        migrations.AlterField(
            model_name='accountpermission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='accountpermission',
            name='permissionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Permission', verbose_name='İzin Adı'),
        ),
        migrations.AlterField(
            model_name='accountpermission',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='accountpermission',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı'),
        ),
        migrations.AlterField(
            model_name='group',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=254, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='group',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='slug',
            field=models.SlugField(max_length=254, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Güncelleme'),
        ),
    ]
