# Generated by Django 3.0.2 on 2020-05-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppermission',
            name='groupId',
        ),
        migrations.RemoveField(
            model_name='grouppermission',
            name='permissionId',
        ),
        migrations.AlterField(
            model_name='group',
            name='createdDate',
            field=models.DateTimeField(verbose_name='Created Date'),
        ),
        migrations.DeleteModel(
            name='AccountPermission',
        ),
        migrations.DeleteModel(
            name='GroupPermission',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
