# Generated by Django 3.0.2 on 2020-03-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='phoneNumber',
        ),
    ]
