# Generated by Django 3.0.2 on 2020-03-15 16:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20200315_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketNumber',
            field=models.PositiveIntegerField(auto_created=True, unique=True, verbose_name='Ticket Numarası'),
        ),
    ]
