# Generated by Django 3.0.2 on 2020-03-15 17:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track', '0003_auto_20200315_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Yorum Id')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updatedDate', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Like')),
                ('creator', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('ticketId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='track.Ticket', verbose_name='Ticket Id')),
            ],
            options={
                'db_table': 'TicketReply',
                'ordering': ['-createdDate'],
            },
        ),
    ]
