# Generated by Django 3.0.2 on 2020-05-29 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20200505_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreply',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='track.TicketReply'),
        ),
    ]
