# Generated by Django 3.0.2 on 2020-05-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_ticketreply_parentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='parentId',
        ),
    ]
